fragment ColumnLayout on contentBlocks_columnLayout_BlockType {
  id
  sectionTitles {
    ...SectionTitles
  }
  columnSectionLayout {
    ...ColumnSectionLayouts
  }
  showDivider
  sectionBackground
}
