fragment InformationGridLayout on contentBlocks_informationGridLayout_BlockType {
  id
  sectionTitles {
    ...SectionTitles
  }
  informationGridLayout {
    ...InformationGridLayouts
  }
  asCards
  asSlider
  sectionBackground
}
