fragment MatrixBlocks on MatrixBlockInterface {
  ...FullWidthSection
  ...ColumnLayout
  ...InformationGridLayout
  ...TabbedContent
  ...Form
  ...TestimonialsCarousel
  ...FaqsSection
  ...EntriesCarousel
  ...LogoCarouselSection
  ...RedactorSection
  ...QuoteSection
  ...LargeImageSection
  ...Calculator
}
