fragment FormFragment on FormInterface {
  id
  title
  handle
  siteId
  csrfToken {
    name
    value
  }
  captchas {
    handle
    name
    value
  }
  settings {
    #   displayFormTitle
    #   displayPageTabs
    #   displayCurrentPageTitle
    #   displayPageProgress
    #   submitMethod
    submitAction
    submitActionTab
    # submitActionUrl
    #   submitActionFormHide
    submitActionMessageHtml
    #   submitActionMessageTimeout
    redirectUrl
    errorMessageHtml
    #   loadingIndicator
    #   loadingIndicatorText
    #   validationOnSubmit
    #   validationOnFocus
    #   defaultLabelPosition
    #   defaultInstructionsPosition
    #   progressPosition
    #   integrations {
    #     settings
    #   }
    redirectEntry {
      id
      uri
      slug
      sectionHandle
    }
  }
  pages {
    name
    id
    settings {
      submitButtonLabel
      backButtonLabel
      showBackButton
      buttonsPosition
    }
    rows {
      rowFields {
        ...FieldFragment
        # ... on Field_Repeater {
        #   fields {
        #     ...FieldFragment
        #   }
        # }
        # ... on Field_Group {
        #   fields {
        #     ...FieldFragment
        #   }
        # }
      }
    }
  }
}
