query GetEntriesBySection($section: [String!], $limit: Int) {
  entries(section: $section, limit: $limit) {
    id
    uri
    title
    sectionHandle
    ... on caseStudies_default_Entry {
      featureImage {
        id
        alt
        title
        url @transform(handle: "featureImage")
        width @transform(handle: "featureImage")
        height @transform(handle: "featureImage")
      }
      shortDescription
      topics {
        id
        title
        slug
      }
    }
    ... on articles_default_Entry {
      featureImage {
        id
        alt
        title
        url @transform(handle: "featureImage")
        width @transform(handle: "featureImage")
        height @transform(handle: "featureImage")
      }
      shortDescription
      topics {
        id
        title
        slug
      }
      types {
        id
        title
        slug
      }
    }
  }
}
