query getHomepageContent {
  entry(section: "homepage") {
    ... on homepage_homepage_Entry {
      title
      hero {
        ...Hero
      }
      contentBlocks {
        ...MatrixBlocks
      }
    }
  }
}
